apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: database
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://appuser:supersecretpassword@postgres.database.svc.cluster.local:5432/appdb?sslmode=disable"
