grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  nodeSelector:
    agentpool: monpool

  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    nodeSelector:
      agentpool: monpool

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      agentpool: monpool

kube-state-metrics:
  nodeSelector:
    agentpool: monpool

prometheusOperator:
  nodeSelector:
    agentpool: monpool