apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
